import { createContext, useCallback, useContext, useEffect, useState, type ReactNode } from 'react';

export type Language = 'en' | 'mk';

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LANGUAGE_STORAGE_KEY = 'dysnomia_language';
const DEFAULT_LANGUAGE: Language = 'en';

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

// Translation files will be loaded here
const translations: Record<Language, Record<string, Record<string, string>>> = {
  en: {
    common: {
      home: 'Home',
      shop: 'Shop',
      collections: 'Collections',
      newArrivals: 'New Arrivals',
      kidsPictures: 'Kids Pictures',
      topSellers: 'Top Sellers',
      aboutUs: 'About Us',
      aboutDysnomia: 'About Dysnomia',
      ourProducts: 'Our Products',
      about: 'About',
      blog: 'Blog',
      cart: 'Cart',
      checkout: 'Checkout',
      wishlist: 'Wishlist',
      search: 'Search',
      account: 'Account',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
      continueShopping: 'Continue Shopping',
      proceedToCheckout: 'Proceed to Checkout',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      cancel: 'Cancel',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      view: 'View',
      close: 'Close',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      submit: 'Submit',
      required: 'Required',
      optional: 'Optional',
      viewAll: 'View all',
      pieces: 'pieces',
      collection: 'Collection',
      exploreOurCollections: 'Explore Our Collections',
      collectionsDescription: 'Our collections embody categories with their own visual style and atmosphere. Each collection is a journey through contemporary art, offering a unique experience that enriches your space and brings inspiration into everyday life.',
      cover: 'Cover',
      exploreTheCollection: 'Explore the collection',
      artworks: 'Artworks',
      loadMore: 'Load More',
      noArtworksYet: 'No artworks yet',
      noArtworksYetDesc: 'This collection doesn\'t have any artworks linked yet.',
      browseAllArtworks: 'Browse All Artworks',
      unableToLoadArtworks: 'Unable to load artworks',
    },
    home: {
      // Hero
      tagline: 'Art • Design • Lifestyle',
      heroDescription: 'Where contemporary art meets modern living. Discover exclusive artworks, crafted with care, style, and sustainability.',
      exploreCollection: 'Explore Collection',
      ourStory: 'Our Story',
      scroll: 'Scroll',
      // USP Section
      whyChoose: 'Why Choose',
      contemporaryArt: 'Contemporary Art',
      contemporaryArtDesc: 'An exclusive collection of digital illustrations.',
      uniqueArtworks: 'Innovative Art',
      uniqueArtworksDesc: 'Visionary creations by talented artists.',
      designAesthetics: 'Design & Aesthetics',
      designAestheticsDesc: 'Style that transforms your space',
      ecoFriendly: 'Eco-Responsible',
      ecoFriendlyDesc: 'Materials and processes in harmony with nature.',
      homeDecor: 'Wall Art',
      homeDecorDesc: 'Visual accents that bring harmony to every environment.',
      // Gallery Tour
      exploreOurWorld: 'Explore Our World',
      galleryTour: 'Gallery',
      galleryTourAccent: 'Tour',
      galleryTourDesc: 'Discover our exclusive collections, directly from the Dysnomia catalog.',
      featuredSeries: 'Featured Series',
      curatedSet: 'Curated Set',
      viewCollection: 'View Collection',
      viewAllCollections: 'View All Collections',
      collectionsEmpty: 'Curated collections will appear here once you create them.',
      // Brand Story
      ourStoryLabel: 'Our Story',
      aboutDysnomia: 'About Dysnomia',
      brandStoryP1: 'Dysnomia Art Gallery is a contemporary art space where art, design, and lifestyle intertwine in harmony. We offer exclusive artworks created with refined style and premium materials.',
      brandStoryP2: 'With an emphasis on aesthetics, sustainable production, and original design, Dysnomia brings harmony and inspiration into every space. Our exclusive collection features contemporary art, carefully selected to transform your interiors.',
      brandStoryP3: 'We believe that art unites people and draws attention in the modern world. That is why we collaborate directly with talented artists from across the globe, offering artistic editions that embody authenticity and value.',
      brandQuote: 'Where contemporary art meets modern living',
      brandSupport: 'Need assistance? Our support team is here to help you find the perfect pieces for your home or office.',
      // Product Carousel
      featuredArtworks: 'Featured Artworks',
      limitedEdition: 'Limited Edition',
      featuredEmpty: 'Featured artworks will appear here once you mark products as featured.',
      roomPreview: 'Room Preview',
    },
    product: {
      addToCart: 'Add to Cart',
      addToWishlist: 'Add to Wishlist',
      removeFromWishlist: 'Remove from Wishlist',
      selectSize: 'Select Size',
      selectType: 'Select Print Type',
      inStock: 'In Stock',
      outOfStock: 'Out of Stock',
      sold: 'Sold',
      price: 'Price',
      quantity: 'Quantity',
      total: 'Total',
      description: 'Description',
      details: 'Details',
      frames: 'Frames',
      deliveryReturns: 'Shipping',
      support: 'Support',
      sizeGuide: 'Size Guide',
      productId: 'Product ID',
      originalArtwork: 'Original Artwork',
      clickToZoom: 'Click to zoom',
      backToGallery: 'Back to Gallery',
      artworkNotFound: 'Artwork Not Found',
      artworkNotFoundDesc: 'The artwork you\'re looking for doesn\'t exist or has been removed.',
      soldMessage: 'This artwork has been sold. Contact us for similar pieces or to commission a custom work.',
      added: 'Added!',
      printType: 'Print Type',
      frameColor: 'Frame Color',
      size: 'Size',
      colorGold: 'Gold',
      colorSilver: 'Silver',
      colorWhite: 'White',
      colorBlack: 'Black',
    },
    cart: {
      yourCart: 'Your Cart',
      emptyCart: 'Your cart is empty',
      emptyCartMessage: 'Looks like you haven\'t added anything to your cart yet.',
      subtotal: 'Subtotal',
      shipping: 'Shipping',
      shippingCalculated: 'Calculated at checkout',
      total: 'Total',
      removeItem: 'Remove item',
      updateQuantity: 'Update quantity',
    },
    checkout: {
      checkout: 'Checkout',
      contactInfo: 'Contact Information',
      shippingAddress: 'Shipping Address',
      orderNotes: 'Order Notes',
      paymentMethod: 'Payment Method',
      payOnDelivery: 'Pay on Delivery',
      payOnDeliveryDesc: 'Pay with cash when your order arrives',
      placeOrder: 'Place Order',
      orderSummary: 'Order Summary',
      email: 'Email',
      phone: 'Phone',
      fullName: 'Full Name',
      address: 'Address',
      city: 'City',
      postalCode: 'Postal Code',
      country: 'Country',
      orderNotesPlaceholder: 'Notes about your order (optional)',
    },
    order: {
      orderConfirmation: 'Order Confirmation',
      thankYou: 'Thank you for your order!',
      orderNumber: 'Order Number',
      orderReceived: 'We\'ve received your order and will contact you shortly.',
      orderDetails: 'Order Details',
      status: 'Status',
      pending: 'Pending',
      confirmed: 'Confirmed',
      shipped: 'Shipped',
      delivered: 'Delivered',
      cancelled: 'Cancelled',
    },
    reviews: {
      reviews: 'Reviews',
      writeReview: 'Write a Review',
      noReviews: 'No reviews yet',
      beFirstToReview: 'Be the first to review this product',
      rating: 'Rating',
      reviewTitle: 'Review Title',
      reviewContent: 'Your Review',
      submitReview: 'Submit Review',
      thankYouReview: 'Thank you for your review!',
      reviewPending: 'Your review is pending approval.',
    },
    account: {
      myAccount: 'My Account',
      orderHistory: 'Order History',
      savedItems: 'Saved Items',
      settings: 'Settings',
      noOrders: 'You haven\'t placed any orders yet.',
    },
    auth: {
      signIn: 'Sign In',
      signUp: 'Sign Up',
      forgotPassword: 'Forgot Password?',
      resetPassword: 'Reset Password',
      emailAddress: 'Email Address',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      createAccount: 'Create Account',
      alreadyHaveAccount: 'Already have an account?',
      dontHaveAccount: 'Don\'t have an account?',
    },
    about: {
      label: 'About Us',
      heroTitle: 'A place where art and design become part of everyday life.',
      heroP1: 'Dysnomia is a Macedonian brand that brings carefully crafted and unique art prints. Our curious and creative team, based in Gevgelija, North Macedonia, believes in diversity, value, and quality. United by our love for art, we are inspired to discover new paths and expressions. What guides us is our pursuit of aesthetics, sustainability, and original design – creating visionary works that inspire, challenge, and infuse fresh energy into everyday life.',
      heroP2: '',
      exploreArtworks: 'Explore Artworks',
      viewCollections: 'View Collections',
      ourMission: 'Our Mission',
      missionQuote: 'What guides us is our inspiration to create works that transform everyday life into a place of beauty.',
      ourValues: 'Our Values',
      whatWeStandFor: 'What guides us',
      valuesDescription: 'Every work we create reflects our commitment to quality, sustainability, and original design. These principles are our direction in everything we do.',
      affordableArt: 'Accessible Art',
      affordableArtDesc: 'Gallery-quality art at prices that inspire trust. We believe beauty should not be a luxury – everyone deserves to live with art they love.',
      madeToOrder: 'Made to order',
      madeToOrderDesc: 'Each piece is created exclusively for you – no mass production, no stockpiling. Your art comes to life with intention and care at the moment you order it.',
      transformSpace: 'Transform Any Space',
      transformSpaceDesc: 'Art is designed to bring new energy and harmony into the atmosphere around you. The right piece reshapes perception and enriches the space with a new dimension.',
      boldExpression: 'Personal Expression',
      boldExpressionDesc: 'Your walls carry your story. We create art that reflects your personality and adds character – pieces that inspire conversation and leave a lasting impression.',
      ourStory: 'Our Story',
      fromPassion: 'From Vision to Gallery',
      storyP1: 'Dysnomia was founded on the conviction that beauty should be part of everyday life. What began as a carefully selected collection of artworks has grown into a gallery that inspires art lovers worldwide.',
      storyP2: 'Today, we continue to discover unique artworks that unite modern aesthetics with timeless charm. Each work is chosen for its power to transform spaces and inspire the world around us.',
      discoverCollections: 'Discover Our Collections',
      getInTouch: 'Get in Touch',
      loveToHear: 'Always here for you',
      contactDescription: 'If you have questions regarding our contemporary art, need assistance in selecting the ideal artwork for your space, or are considering a custom project – we are here to provide support and inspiration.',
      contactUs: 'Contact Us',
      email: 'Email',
      location: 'Location',
      locationValue: 'Skopje, North Macedonia',
      shippingWorldwide: 'Shipping Worldwide',
      followUs: 'Follow Us',
    },
    shop: {
      shopTitle: 'Shop',
      shopTitleAccent: 'All',
      shopDescription: 'Welcome to our online shop, where art meets contemporary style. Discover carefully selected digital creations that bring harmony, elegance, and inspiration into every space.',
      shopSlogan: 'Art that transforms every space.',
      filters: 'Filters',
      artwork: 'artwork',
      artworks: 'artworks',
      sortBy: 'Sort by:',
      sortNewest: 'Newest',
      sortPriceLow: 'Price: Low to High',
      sortPriceHigh: 'Price: High to Low',
      sortName: 'Name A-Z',
      clearAllFilters: 'Clear All Filters',
      clearFilters: 'Clear Filters',
      collectionsFilter: 'Collections',
      priceFilter: 'Price',
      allPrices: 'All Prices',
      under100: 'Under €100',
      price100to200: '€100 - €200',
      price200to300: '€200 - €300',
      over300: 'Over €300',
      specialOffers: 'Special Offers',
      onSale: 'On Sale',
      failedToLoad: 'Failed to load artworks',
      tryAgain: 'Try Again',
      noArtworksFound: 'No artworks found',
      noArtworksFoundDesc: 'Try adjusting your filters to find what you\'re looking for.',
      loadMore: 'Load More',
      showing: 'Showing',
      of: 'of',
      badgeNew: 'New',
      badgeArtist: 'Artist',
      badgeLimited: 'Limited',
      badgeBestseller: 'Bestseller',
    },
    newArrivals: {
      title: 'Exclusive',
      heroTitle: 'New',
      heroTitleAccent: 'Arrivals',
      heroDescription: 'Explore our latest collection of unique artworks. Carefully selected to bring modern elegance and inspiring beauty, they enrich every space with style and harmony.',
      browseAll: 'Browse All',
      viewCollections: 'View Collections',
      featured: 'Featured',
      noArtworks: 'No artworks found',
      noArtworksMessage: 'Check back soon for new arrivals.',
    },
    kidsPictures: {
      title: 'Kids Pictures',
      heroTitle: 'Playful',
      heroTitleAccent: 'Artworks',
      heroDescription: 'Brighten up your little one\'s room with our charming kids collection. Fun, colorful prints designed to inspire imagination and creativity.',
      browseAll: 'Browse All',
      viewCollections: 'View Collections',
      featured: 'Featured',
      noArtworks: 'No artworks found',
      noArtworksMessage: 'Check back soon for new kids pictures.',
    },
    topSellers: {
      title: 'Top Sellers',
      heroTitle: 'Customer',
      heroTitleAccent: 'Favorites',
      heroDescription: 'Discover our most loved artworks. These bestselling pieces have captured the hearts of art enthusiasts and transformed countless spaces into stunning galleries.',
      shopAll: 'Shop All',
      viewCollections: 'View Collections',
      featuredLabel: '#1 Bestseller',
      filterAll: 'All Top Sellers',
      filterUnder200: 'Under €200',
      filterUnder500: 'Under €500',
      filterPremium: 'Premium',
      artwork: 'artwork',
      artworks: 'artworks',
      noArtworks: 'No artworks found',
      noArtworksMessage: 'Try adjusting your filters to find what you\'re looking for.',
      clearFilters: 'Clear Filters',
      whyChooseUs: 'Why Choose Us',
      trustedByThousands: 'Trusted by Thousands',
      curatedSelection: 'Curated Selection',
      curatedSelectionDesc: 'Every piece is handpicked by our expert curators for quality and style.',
      freeShipping: 'Delivery',
      freeShippingDesc: 'Delivery for all artworks is charged at 150 MKD, regardless of format or size.',
      premiumQuality: 'Premium Quality',
      premiumQualityDesc: 'Gallery-grade prints on archival paper with museum-quality frames.',
    },
    footer: {
      shop: 'Inspiration',
      about: 'About',
      support: 'Support',
      connect: 'Connect',
      allArtworks: 'All Artworks',
      shippingPolicy: 'Shipping Policy',
      returnPolicy: 'Return Policy',
      faq: 'FAQ',
      privacyPolicy: 'Privacy Policy',
      regionCurrency: 'EU | EUR',
      copyright: 'Copyright',
      rightsReserved: 'Dysnomia Art Gallery. All rights reserved.',
    },
    blog: {
      title: 'Art and Inspiration',
      heroTitle: 'Art and',
      heroTitleAccent: 'Inspiration',
      heroDescription: 'Contemporary art that brings inspiration for interiors and fresh ideas for modern design.',
      readMore: 'Read More',
      backToBlog: 'Back to Blog',
      by: 'By',
      publishedOn: 'Published on',
      noPosts: 'No posts yet',
      noPostsMessage: 'Check back soon for new stories and insights.',
      postNotFound: 'Post Not Found',
      postNotFoundDesc: 'The blog post you\'re looking for doesn\'t exist or has been removed.',
      draft: 'Draft',
      published: 'Published',
      minuteRead: 'min read',
    },
    contact: {
      subtitle: 'Get in Touch',
      title: 'Contact Us',
      description: 'Have a question or need assistance? Reach out to us through any of the channels below.',
      email: 'Email',
    },
    shipping: {
      title: 'Return and Exchange Policy',
      description: 'Each artwork is thoughtfully selected and created to bring you joy and inspiration. If you are not completely satisfied with your purchase, you have the right to return or exchange the piece in its original condition within 14 days of receipt.',
      returnsLabel: 'Returns',
      returnsText: 'Upon receipt and inspection of the artwork, a full refund will be issued. Refunds are processed within 5–7 business days.',
      exchangesLabel: 'Exchanges',
      exchangesText: 'You may choose another artwork from our collection. If there is a price difference, it will be appropriately adjusted.',
      conditionLabel: 'Condition of the Artwork',
      conditionText: 'We accept returns only for artworks that are undamaged, unused, and in their original packaging.',
      costsLabel: 'Return and Exchange Costs',
      costsText: 'Shipping costs for returns or exchanges are the responsibility of the customer, unless the artwork arrives damaged or defective.',
      closingText: 'Our goal is for every purchase to be secure, transparent, and bring you complete satisfaction.',
      processingTitle: 'Processing Time',
      processingText1: 'All artworks are made to order and carefully prepared just for you. Please allow 2–4 business days for your order to be ready before shipping.',
      processingText2: 'During holidays or promotional periods, processing time may be slightly longer. You will be notified via email.',
    },
  },
  mk: {
    common: {
      home: 'Дома',
      shop: 'Продавница',
      collections: 'Колекции',
      newArrivals: 'Нови Производи',
      kidsPictures: 'Детски Слики',
      topSellers: 'Најпродавани',
      aboutUs: 'За Нас',
      aboutDysnomia: 'За Dysnomia',
      ourProducts: 'Наши Производи',
      about: 'За Нас',
      blog: 'Блог',
      cart: 'Кошничка',
      checkout: 'Наплата',
      wishlist: 'Листа на Желби',
      search: 'Пребарај',
      account: 'Сметка',
      login: 'Најава',
      register: 'Регистрација',
      logout: 'Одјава',
      continueShopping: 'Продолжи со Купување',
      proceedToCheckout: 'Продолжи кон Наплата',
      loading: 'Се вчитува...',
      error: 'Грешка',
      success: 'Успешно',
      cancel: 'Откажи',
      save: 'Зачувај',
      delete: 'Избриши',
      edit: 'Уреди',
      view: 'Прегледај',
      close: 'Затвори',
      back: 'Назад',
      next: 'Следно',
      previous: 'Претходно',
      submit: 'Поднеси',
      required: 'Задолжително',
      optional: 'Опционално',
      viewAll: 'Прегледај сè',
      pieces: 'парчиња',
      collection: 'Колекција',
      exploreOurCollections: 'Истражете Ги Нашите Колекции',
      collectionsDescription: 'Нашите колекции претставуваат категории со сопствен визуелен стил и атмосфера. Секоја колекција е патување низ современата уметност, создавајќи уникатно искуство што го збогатува просторот и внесува инспирација во секојдневието.',
      cover: 'Корица',
      exploreTheCollection: 'Истражете ја колекцијата',
      artworks: 'Уметнички Дела',
      loadMore: 'Прикажи Повеќе',
      noArtworksYet: 'Сè уште нема уметнички дела',
      noArtworksYetDesc: 'Оваа колекција сè уште нема поврзани уметнички дела.',
      browseAllArtworks: 'Прегледај Ги Сите Дела',
      unableToLoadArtworks: 'Не можат да се вчитаат уметничките дела',
    },
    home: {
      // Hero
      tagline: 'Уметност • Дизајн • Животен Стил',
      heroDescription: 'Каде современата уметност се среќава со модерното живеење. Откријте ексклузивни уметнички дела, создадени со внимание, стил и одржливост.',
      exploreCollection: 'Истражи Колекција',
      ourStory: 'Нашата Приказна',
      scroll: 'Скролај',
      // USP Section
      whyChoose: 'Зошто Да Изберете',
      contemporaryArt: 'Современа Уметност',
      contemporaryArtDesc: 'Ексклузивна колекција на дигитални илустрации.',
      uniqueArtworks: 'Иновативна Уметност',
      uniqueArtworksDesc: 'Визионерски креации од талентирани уметници.',
      designAesthetics: 'Дизајн и Естетика',
      designAestheticsDesc: 'Стил што го трансформира вашиот простор',
      ecoFriendly: 'Еко-Одговорни',
      ecoFriendlyDesc: 'Материјали и процеси во хармонија со природата.',
      homeDecor: 'Ѕидна Уметност',
      homeDecorDesc: 'Визуелни акценти што внесуваат хармонија во секоја средина.',
      // Gallery Tour
      exploreOurWorld: 'Истражете Го Нашиот Свет',
      galleryTour: 'Галериска',
      galleryTourAccent: 'Тура',
      galleryTourDesc: 'Откријте ги нашите ексклузивни колекции, директно од каталогот на Dysnomia.',
      featuredSeries: 'Истакната Серија',
      curatedSet: 'Курирана Колекција',
      viewCollection: 'Прегледај Колекција',
      viewAllCollections: 'Прегледај Сите Колекции',
      collectionsEmpty: 'Курираните колекции ќе се појават тука откако ќе ги креирате.',
      // Brand Story
      ourStoryLabel: 'Нашата Приказна',
      aboutDysnomia: 'За Dysnomia',
      brandStoryP1: 'Dysnomia Art Gallery е современ уметнички простор каде уметноста, дизајнот и животниот стил се преплетуваат во хармонија. Нудиме ексклузивни уметнички дела создадени со префинет стил и врвни материјали.',
      brandStoryP2: 'Со акцент на естетика, одржливо производство и оригинален дизајн, Dysnomia внесува хармонија и инспирација во секој простор. Нашата ексклузивна колекција опфаќа современа уметност, внимателно избрана да ги трансформира вашите ентериери.',
      brandStoryP3: 'Веруваме дека уметноста ги обединува луѓето и привлекува внимание во современиот свет. Затоа соработуваме директно со талентирани уметници од различни земји, нудејќи уметнички изданија што носат автентичност и вредност.',
      brandQuote: 'Каде современата уметност се среќава со модерното живеење',
      brandSupport: 'Ви треба помош? Нашиот тим за поддршка е тука да ви помогне да ги најдете совршените парчиња за вашиот дом или канцеларија.',
      // Product Carousel
      featuredArtworks: 'Истакнати Дела',
      limitedEdition: 'Лимитирано Издание',
      featuredEmpty: 'Истакнатите уметнички дела ќе се појават тука откако ќе означите производи како истакнати.',
      roomPreview: 'Преглед во Соба',
    },
    product: {
      addToCart: 'Додај во Кошничка',
      addToWishlist: 'Додај во Листа на Желби',
      removeFromWishlist: 'Отстрани од Листа на Желби',
      selectSize: 'Избери Големина',
      selectType: 'Избери Тип на Печатење',
      inStock: 'На Залиха',
      outOfStock: 'Нема на Залиха',
      sold: 'Продадено',
      price: 'Цена',
      quantity: 'Количина',
      total: 'Вкупно',
      description: 'Опис',
      details: 'Детали',
      frames: 'Рамки',
      deliveryReturns: 'Достава',
      support: 'Поддршка',
      sizeGuide: 'Водич за Големина',
      productId: 'ID на Производ',
      originalArtwork: 'Оригинално Уметничко Дело',
      clickToZoom: 'Кликни за зумирање',
      backToGallery: 'Назад кон Галерија',
      artworkNotFound: 'Уметничкото дело не е пронајдено',
      artworkNotFoundDesc: 'Уметничкото дело што го барате не постои или е отстрането.',
      soldMessage: 'Ова уметничко дело е продадено. Контактирајте нè за слични парчиња или за нарачка по мерка.',
      added: 'Додадено!',
      printType: 'Тип на Печатење',
      frameColor: 'Боја на Рамка',
      size: 'Големина',
      colorGold: 'Златна',
      colorSilver: 'Сребрена',
      colorWhite: 'Бела',
      colorBlack: 'Црна',
    },
    cart: {
      yourCart: 'Твојата Кошничка',
      emptyCart: 'Твојата кошничка е празна',
      emptyCartMessage: 'Изгледа дека сè уште немаш додадено ништо во кошничката.',
      subtotal: 'Меѓузбир',
      shipping: 'Достава',
      shippingCalculated: 'Пресметано при наплата',
      total: 'Вкупно',
      removeItem: 'Отстрани производ',
      updateQuantity: 'Ажурирај количина',
    },
    checkout: {
      checkout: 'Наплата',
      contactInfo: 'Контакт Информации',
      shippingAddress: 'Адреса за Достава',
      orderNotes: 'Забелешки за Нарачката',
      paymentMethod: 'Начин на Плаќање',
      payOnDelivery: 'Плаќање при Достава',
      payOnDeliveryDesc: 'Плати во готово кога ќе пристигне нарачката',
      placeOrder: 'Направи Нарачка',
      orderSummary: 'Преглед на Нарачка',
      email: 'Е-пошта',
      phone: 'Телефон',
      fullName: 'Целосно Име',
      address: 'Адреса',
      city: 'Град',
      postalCode: 'Поштенски Код',
      country: 'Држава',
      orderNotesPlaceholder: 'Забелешки за нарачката (опционално)',
    },
    order: {
      orderConfirmation: 'Потврда на Нарачка',
      thankYou: 'Ви благодариме за нарачката!',
      orderNumber: 'Број на Нарачка',
      orderReceived: 'Ја примивме вашата нарачка и ќе ве контактираме наскоро.',
      orderDetails: 'Детали за Нарачка',
      status: 'Статус',
      pending: 'Во Обработка',
      confirmed: 'Потврдено',
      shipped: 'Испратено',
      delivered: 'Доставено',
      cancelled: 'Откажано',
    },
    reviews: {
      reviews: 'Рецензии',
      writeReview: 'Напиши Рецензија',
      noReviews: 'Сè уште нема рецензии',
      beFirstToReview: 'Биди прв што ќе остави рецензија за овој производ',
      rating: 'Оценка',
      reviewTitle: 'Наслов на Рецензија',
      reviewContent: 'Твојата Рецензија',
      submitReview: 'Поднеси Рецензија',
      thankYouReview: 'Ви благодариме за рецензијата!',
      reviewPending: 'Вашата рецензија чека одобрување.',
    },
    account: {
      myAccount: 'Моја Сметка',
      orderHistory: 'Историја на Нарачки',
      savedItems: 'Зачувани Производи',
      settings: 'Поставки',
      noOrders: 'Сè уште немате направено нарачки.',
    },
    auth: {
      signIn: 'Најави се',
      signUp: 'Регистрирај се',
      forgotPassword: 'Заборавена Лозинка?',
      resetPassword: 'Ресетирај Лозинка',
      emailAddress: 'Е-пошта',
      password: 'Лозинка',
      confirmPassword: 'Потврди Лозинка',
      createAccount: 'Креирај Сметка',
      alreadyHaveAccount: 'Веќе имаш сметка?',
      dontHaveAccount: 'Немаш сметка?',
    },
    about: {
      label: 'За Нас',
      heroTitle: 'Место каде уметноста и дизајнот стануваат дел од секојдневниот живот.',
      heroP1: 'Dysnomia е македонски бренд што носи внимателно создадени и уникатни уметнички принтови. Нашиот љубопитен и креативен тим, со седиште во Гевгелија, Северна Македонија, верува во разновидност, вредност и квалитет. Обединети од љубовта кон уметноста, инспирацијата ни е да откриваме нови патеки и изрази. Она што нè води е стремежот кон естетика, одржливост и оригинален дизајн – создавајќи визионерски дела што инспирираат, предизвикуваат и внесуваат свежа енергија во секојдневниот живот.',
      heroP2: '',
      exploreArtworks: 'Истражи Уметнички Дела',
      viewCollections: 'Прегледај Колекции',
      ourMission: 'Нашата Мисија',
      missionQuote: 'Она што нè води е нашата инспирација да создадеме дела што го претвораат секојдневието во место на убавина.',
      ourValues: 'Нашите Вредности',
      whatWeStandFor: 'Она што нè води',
      valuesDescription: 'Секое дело што го создадаваме ја одразува нашата посветеност кон квалитет, одржливост и оригинален дизајн. Овие принципи се нашата насока во секое создавање.',
      affordableArt: 'Достапна Уметност',
      affordableArtDesc: 'Уметност со галериски квалитет по цени што инспирираат доверба. Веруваме дека убавината не треба да биде луксуз – секој заслужува да живее со уметност што ја сака.',
      madeToOrder: 'Изработено по нарачка',
      madeToOrderDesc: 'Секое дело е создадено исклучиво за вас – без сериско производство, без складирање. Вашата уметност оживува со намера и грижа во моментот кога ја нарачувате.',
      transformSpace: 'Трансформирај го просторот',
      transformSpaceDesc: 'Уметност создадена да внесе нова енергија и хармонија во атмосферата што ве опкружува. Вистинското дело ја менува перцепцијата и го обогатува просторот со нова димензија.',
      boldExpression: 'Лично изразување',
      boldExpressionDesc: 'Вашите ѕидови ја носат вашата приказна. Создаваме уметност што ја одразува вашата личност и внесува карактер – дела што инспирираат разговор и оставаат траен впечаток.',
      ourStory: 'Нашата Приказна',
      fromPassion: 'Од Визија до Галерија',
      storyP1: 'Dysnomia е родена од уверување дека убавината треба да биде дел од секојдневието. Започнавме со внимателно избрана колекција на уметнички дела, која прерасна во галерија што ги инспирира љубителите на уметноста ширум светот.',
      storyP2: 'Денес, продолжуваме да откриваме уникатни уметнички дела што ја спојуваат современата естетика со безвременски шарм. Секое дело е избрано за неговата моќ да го преобрази просторот и да внесе инспирација во светот околу нас.',
      discoverCollections: 'Откријте Ги Нашите Колекции',
      getInTouch: 'Контактирајте Нè',
      loveToHear: 'Секогаш достапни за вас',
      contactDescription: 'Доколку имате прашања во врска со нашата современа уметност, или ви е потребна помош при избор на идеално уметничко дело за вашиот простор или размислувате за проект по нарачка – ние сме тука да ви понудиме поддршка и инспирација.',
      contactUs: 'Контактирајте Нè',
      email: 'Е-пошта',
      location: 'Локација',
      locationValue: 'Скопје, Северна Македонија',
      shippingWorldwide: 'Достава Ширум Светот',
      followUs: 'Следете Нè',
    },
    shop: {
      shopTitle: 'Продавница',
      shopTitleAccent: '',
      shopDescription: 'Добредојдовте во нашата онлајн продавница, место каде уметноста и современиот стил се спојуваат. Тука ќе најдете внимателно избрани дигитални дела што внесуваат хармонија, елеганција и инспирација во секој простор.',
      shopSlogan: 'Уметност што го преобразува секој простор.',
      filters: 'Филтри',
      artwork: 'уметничко дело',
      artworks: 'уметнички дела',
      sortBy: 'Сортирај:',
      sortNewest: 'Најнови',
      sortPriceLow: 'Цена: Ниска кон Висока',
      sortPriceHigh: 'Цена: Висока кон Ниска',
      sortName: 'Име А-Ш',
      clearAllFilters: 'Исчисти Ги Сите Филтри',
      clearFilters: 'Исчисти Филтри',
      collectionsFilter: 'Колекции',
      priceFilter: 'Цена',
      allPrices: 'Сите Цени',
      under100: 'Под €100',
      price100to200: '€100 - €200',
      price200to300: '€200 - €300',
      over300: 'Над €300',
      specialOffers: 'Специјални Понуди',
      onSale: 'На Попуст',
      failedToLoad: 'Не можат да се вчитаат уметничките дела',
      tryAgain: 'Обиди се Повторно',
      noArtworksFound: 'Не се пронајдени уметнички дела',
      noArtworksFoundDesc: 'Пробајте да ги прилагодите филтрите за да го најдете тоа што го барате.',
      loadMore: 'Прикажи Повеќе',
      showing: 'Прикажани',
      of: 'од',
      badgeNew: 'Ново',
      badgeArtist: 'Уметник',
      badgeLimited: 'Лимитирано',
      badgeBestseller: 'Бестселер',
    },
    newArrivals: {
      title: 'Ексклузивни',
      heroTitle: 'Ексклузивни',
      heroTitleAccent: 'Новитети',
      heroDescription: 'Откријте ја нашата најнова колекција на уникатни уметнички дела. Внимателно избрани за да внесат модерна елеганција и инспиративна убавина, тие го збогатуваат секој простор со стил и хармонија.',
      browseAll: 'Прегледај Сè',
      viewCollections: 'Прегледај Колекции',
      featured: 'Истакнато',
      noArtworks: 'Не се пронајдени уметнички дела',
      noArtworksMessage: 'Навратете повторно наскоро за нови производи.',
    },
    kidsPictures: {
      title: 'Детски Слики',
      heroTitle: 'Весели',
      heroTitleAccent: 'Уметнички Дела',
      heroDescription: 'Разубавете ја собата на вашето дете со нашата шармантна детска колекција. Забавни, шарени принтови дизајнирани да инспирираат имагинација и креативност.',
      browseAll: 'Прегледај Сè',
      viewCollections: 'Прегледај Колекции',
      featured: 'Истакнато',
      noArtworks: 'Не се пронајдени уметнички дела',
      noArtworksMessage: 'Навратете повторно наскоро за нови детски слики.',
    },
    topSellers: {
      title: 'Најпродавани',
      heroTitle: 'Омилени',
      heroTitleAccent: 'Производи',
      heroDescription: 'Откријте ги нашите најсакани уметнички дела. Овие бестселери ги освоија срцата на љубителите на уметноста и трансформираа безброј простори во прекрасни галерии.',
      shopAll: 'Купи Сè',
      viewCollections: 'Прегледај Колекции',
      featuredLabel: '#1 Бестселер',
      filterAll: 'Сите Најпродавани',
      filterUnder200: 'Под €200',
      filterUnder500: 'Под €500',
      filterPremium: 'Премиум',
      artwork: 'уметничко дело',
      artworks: 'уметнички дела',
      noArtworks: 'Не се пронајдени уметнички дела',
      noArtworksMessage: 'Пробајте да ги прилагодите филтрите за да го најдете тоа што го барате.',
      clearFilters: 'Исчисти Филтри',
      whyChooseUs: 'Зошто Ние',
      trustedByThousands: 'Доверба од Илјадници',
      curatedSelection: 'Курирана Селекција',
      curatedSelectionDesc: 'Секое парче е рачно избрано од нашите експерти куратори за квалитет и стил.',
      freeShipping: 'Достава',
      freeShippingDesc: 'Доставата на сите слики се наплаќа дополнително 150 денари, независно од форматот или големината.',
      premiumQuality: 'Премиум Квалитет',
      premiumQualityDesc: 'Галериски печатења на архивска хартија со рамки од музејски квалитет.',
    },
    footer: {
      shop: 'Инспирација',
      about: 'За Нас',
      support: 'Поддршка',
      connect: 'Контакт',
      allArtworks: 'Сите Уметнички Дела',
      shippingPolicy: 'Политика за испорака',
      returnPolicy: 'Политика за враќање',
      faq: 'ЧПП',
      privacyPolicy: 'Политика за Приватност',
      regionCurrency: 'ЕУ | ЕУР',
      copyright: 'Авторски права',
      rightsReserved: 'Dysnomia Art Gallery. Сите права се задржани.',
    },
    blog: {
      title: 'Уметност и Инспирација',
      heroTitle: 'Уметност и',
      heroTitleAccent: 'Инспирација',
      heroDescription: 'Современа уметност што носи инспирација за ентериер и свежи идеи за современ дизајн.',
      readMore: 'Прочитај Повеќе',
      backToBlog: 'Назад кон Блог',
      by: 'Од',
      publishedOn: 'Објавено на',
      noPosts: 'Сè уште нема објави',
      noPostsMessage: 'Навратете повторно наскоро за нови приказни и увиди.',
      postNotFound: 'Објавата не е пронајдена',
      postNotFoundDesc: 'Објавата на блогот што ја барате не постои или е отстранета.',
      draft: 'Нацрт',
      published: 'Објавено',
      minuteRead: 'мин читање',
    },
    contact: {
      subtitle: 'Контактирајте Нè',
      title: 'Контакт',
      description: 'Имате прашање или ви треба помош? Контактирајте нè преку било кој од каналите подолу.',
      email: 'Е-пошта',
    },
    shipping: {
      title: 'Политика за враќање и замена',
      description: 'Секое уметничко дело е внимателно избрано и создадено за да ви донесе радост и инспирација. Доколку не сте целосно задоволни од вашата набавка, имате право да го вратите или замените делото во неговата оригинална состојба во рок од 14 дена од приемот.',
      returnsLabel: 'Враќање',
      returnsText: 'По прием и преглед на делото, ќе биде извршен целосен поврат на средствата. Повратите се обработуваат во рок од 5–7 работни дена.',
      exchangesLabel: 'Замена',
      exchangesText: 'Можете да одберете друго уметничко дело од нашата колекција. Доколку постои разлика во цената, таа ќе биде соодветно пресметана.',
      conditionLabel: 'Состојба на делото',
      conditionText: 'Прифаќаме враќање само за дела кои се неоштетени, некористени и во нивната оригинална амбалажа.',
      costsLabel: 'Трошоци за враќање и замена',
      costsText: 'Трошоците за испорака при враќање или замена се на товар на купувачот, освен ако делото не пристигне оштетено или со дефект.',
      closingText: 'Нашата цел е секоја набавка да биде сигурна, транспарентна и да ви донесе целосно задоволство.',
      processingTitle: 'Време на обработка',
      processingText1: 'Сите уметнички дела се изработуваат по нарачка и внимателно се подготвуваат само за вас. Ве молиме дозволете 2–4 работни дена за вашата нарачка да биде подготвена пред испорака.',
      processingText2: 'За време на празници или промотивни периоди, времето на обработка може да биде малку подолго. За тоа ќе бидете навремено известени преку е-пошта.',
    },
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === 'undefined') return DEFAULT_LANGUAGE;
    try {
      const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (stored === 'en' || stored === 'mk') return stored;
      return DEFAULT_LANGUAGE;
    } catch {
      return DEFAULT_LANGUAGE;
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
      document.documentElement.lang = language;
    } catch (error) {
      console.error('Failed to save language to localStorage:', error);
    }
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
  }, []);

  const t = useCallback((key: string): string => {
    const parts = key.split('.');
    if (parts.length !== 2) return key;

    const [namespace, translationKey] = parts;
    const namespaceTranslations = translations[language]?.[namespace];

    if (!namespaceTranslations) return key;
    return namespaceTranslations[translationKey] ?? key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguageContext() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguageContext must be used within a LanguageProvider');
  }
  return context;
}
